# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c99750005c06960fcc1d88a69fc5fde2177aff92b8067b3ca513ae9934d03e4f3dae7843b7600e58483ff75e36b9595c165d9f1339e99eaa9a17349d7bff8b54

test:
  secret_key_base: 7b466d76df6fa73439b81e2a6d9b2fab0e31caf1bc359bce40d12e83365f020f8c0eb08301a4998b3fc74320910e370a4a6687c84dfa4840ebe7cbb4017cfa76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
